version: '2'
services:
  app:
    build: ./app
    ports:
     - "5000:5000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./app:/app
  db:
    build: ./database
